### ISSUE TITLE
Pekko 1.1 snapshots break Pekko Connectors tests

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#1066]
https://github.com/apache/incubator-pekko-connectors/pull/412

Needs investigation before we can release 1.1.0-M1

We are getting NoSuchMethodErrors on some of the pekko utils classes like OptionConverter and FutureConverter.

It could be that we need to rewrite our pekko-connector test builds - to compile with pekko 1.0 but then to test with pekko 1.1.

```
[error] Test docs.javadsl.SnsPublisherTest failed: java.lang.NoSuchMethodError: org.apache.pekko.util.FutureConverters$FutureOps$.asJava$extension(Lscala/concurrent/Future;)Ljava/util/concurrent/CompletionStage;, took 0.0 sec
[error]     at org.apache.pekko.http.javadsl.Http.shutdownAllConnectionPools(Http.scala:798)
[error]     at docs.javadsl.SnsPublisherTest.tearDownAfterClass(SnsPublisherTest.java:71)
```

```
[error] Test docs.javadsl.OpensearchV1Test failed: java.lang.NoSuchMethodError: 'java.util.concurrent.CompletionStage org.apache.pekko.util.FutureConverters$FutureOps$.asJava$extension(scala.concurrent.Future)', took 0.0 sec
[error]     at org.apache.pekko.http.javadsl.Http.singleRequest(Http.scala:643)
```

Issue seems to happen with Scala 3.3 testing but not with Scala 2.12 or 2.13 testing.

This is a command that fails in incubator-pekko-connectors (don't forget to use docker-compose to start all the necessary containers for this connector). 
```
sbt -Dpekko.build.pekko.version=main "++3.3.1 elasticsearch/test"
```

Seems like pekko-http jars built for Scala 3 with Pekko 1.0 jars do not work Pekko 1.1 jars at runtime.

**Comment by He-Pin** [comment]
May because of the inline？@mdedetrich

**Comment by pjfanning** [comment]
The issue is still happening. Please do not close this issue until we have proof that is fixed.

https://github.com/apache/incubator-pekko-connectors/actions/runs/7686045276/job/20961266768

**Comment by mdedetrich** [comment]
> The issue is still happening. Please do not close this issue until we have proof that is fixed.

I didn't intend to close the issue, it auto closed when PR that referenced the issue was merged.

I guess GitHub added "references" as ons of the keywords that causes linked issues to close when PR does, will have to find another word.

**Comment by mdedetrich** [comment]
> The issue is still happening. Please do not close this issue until we have proof that is fixed.

I didn't intend to close the issue, it auto closed when PR that referenced the issue was merged.

I guess GitHub added "references" as ons of the keywords that causes linked issues to close when PR does, will have to find another word.

**Comment by pjfanning** [comment]
I forced new jar publishes of pekko and pekko-http (1.1.x) and am still getting the same issues in pekko-connectors testing

https://github.com/apache/incubator-pekko-connectors/actions/runs/7694171655/job/20964422587

**Comment by mdedetrich** [comment]
> I don't want us to be forced into releasing a whole set 1.1 releases for all our repos after we do a pekko (core) 1.1 release.

As you can tell we are already have an entire matrix that will reveal any such issues, ontop of this its an M1 and not a full release. Lets wait till the snapshots are published and propagated as discussed and not do anything rash

**Comment by pjfanning** [comment]
@mdedetrich see https://github.com/apache/incubator-pekko/issues/1066#issuecomment-1914347348 (TLDR - I have tested this)

The main issues are with 
```
org.apache.pekko.util.FutureConverters$FutureOps$
```

Could we just undo the changes that caused this set of bin incompatibilities.

**Comment by mdedetrich** [comment]
Sure, let me double check that everything compiled/propagated properly and ill set up a PR if thats the case

**Comment by mdedetrich** [comment]
Okay the `@targetName` indeed doesn't work as expected, will remove the `inline def`

**Comment by mdedetrich** [comment]
I triggered a snapshot deploy

**Comment by He-Pin** [comment]
Maybe we can backport this to 1.0.x one day, then it will works

**Comment by pjfanning** [comment]
No back port unless it is with new functions. Existing functions cannot be changed due to binary compatibility reasons.

**Comment by He-Pin** [comment]
> No back port unless it is with new functions. Existing functions cannot be changed due to binary compatibility reasons.

Oh, yes, users can use it too.

**Comment by mdedetrich** [comment]
> Oh, yes, users can use it too.

They shouldn't be, this is private API

But yes if we create new functions we can then propagate those functions to all of the pekko projects but tbh I am not inclined to do this, we have bigger problems and I have spent enough time (as well as others) on this.

**Comment by He-Pin** [comment]
I mean use pekko 1.0.0 with newer connectors

**Comment by He-Pin** [comment]
It's scala3' inline problem and can't generate bytes code for Java usages,  it's a Scala 3's problem. 

Let's defer this in pekko 2.0, when we will have a good start.

**Comment by He-Pin** [comment]
And as a  frontier,  you always hit something, who is using scala3 ' inline for some large cross projects like this？AFAIK, no one and you are the first one. So @mdedetrich Still excellent job

**Comment by mdedetrich** [comment]
Re-running pekko-connectors CI now, see https://github.com/apache/incubator-pekko-connectors/actions/runs/7694171655

**Comment by He-Pin** [comment]
Seems it's ok now.

**Comment by mdedetrich** [comment]
So only https://github.com/apache/incubator-pekko-connectors/actions/runs/7694171655/job/20969131574 has failed but it seems the cause is erroneous and may already be fixed in `main`.

@pjfanning Do you want to confirm? Feel free to close the issue as completed if there are no more issues.

**Comment by He-Pin** [comment]
It's an already known issue, I think we can close this issue now.
