### PR TITLE
chore: Fix ActorDocSpec on Scala 3.3

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Fix ActorDocSpec

refs: https://github.com/apache/incubator-pekko/issues/1081

### CODE REVIEW

**Comment by pjfanning** [comment]
This definitely compiles on Scala 2.12 and 2.13 as well?

**Comment by He-Pin** [comment]
@pjfanning Runtime error on Scala 3.3

**Comment by mdedetrich** [comment]
To clarify, is this fixing a compilation error that existed on Scala 3.3 or was the test (and possibly Pekko) running differently on Scala 3.3?

**Comment by mdedetrich** [comment]
> @pjfanning Runtime error on Scala 3.3

We should probably report this on Dotty/Scala 3 then

**Comment by He-Pin** [comment]
@mdedetrich @pjfanning runtime error, compiles fine.

**Comment by He-Pin** [comment]
I was encounter https://github.com/lampepfl/dotty/issues/16018 too.

**Comment by He-Pin** [comment]
I will schedule a Test run locally on Scala 3.3
